# Generated by Django 5.0.7 on 2024-07-11 11:35

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingParameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="mailing_no_name",
                        max_length=150,
                        verbose_name="Название рассылки",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="начало рассылки",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024,
                            7,
                            12,
                            11,
                            35,
                            20,
                            101825,
                            tzinfo=datetime.timezone.utc,
                        ),
                        verbose_name="конец рассылки",
                    ),
                ),
                (
                    "next_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата следующей рассылки",
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("daily", "Ежедневно"),
                            ("weekly", "Еженедельно"),
                            ("monthly", "Ежемесячно"),
                        ],
                        default="daily",
                        max_length=50,
                        verbose_name="Интервал рассылки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активен"),
                            ("inactive", "Неактивен"),
                            ("finished", "закончен успешно"),
                            ("finished_date", "закончен в срок"),
                            ("finished_error", "закончен с ошибками"),
                        ],
                        default="not_active",
                        max_length=50,
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "client",
                    models.ManyToManyField(
                        to="client.client", verbose_name="Получатель"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Параметры рассылки",
                "verbose_name_plural": "Параметры рассылок",
                "permissions": [("change_status", "Can change status")],
            },
        ),
        migrations.CreateModel(
            name="Logs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_time_sending",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="время последней рассылки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "response",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Ответ почтового сервера",
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.mailingparameters",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог рассылки",
                "verbose_name_plural": "Логи рассылок",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Тема письма",
                    ),
                ),
                ("content", models.TextField(verbose_name="Содержание письма")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
            },
        ),
        migrations.AddField(
            model_name="mailingparameters",
            name="mail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mailing.message",
                verbose_name="Тема письма",
            ),
        ),
    ]
