# Generated by Django 4.2.2 on 2024-07-12 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_mailingparameters_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingparameters",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 13, 14, 29, 18, 403101, tzinfo=datetime.timezone.utc
                ),
                verbose_name="конец рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailingparameters",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Активен"),
                    ("inactive", "Неактивен"),
                    ("finished", "закончен успешно"),
                    ("finished_date", "закончен в срок"),
                    ("finished_error", "закончен с ошибками"),
                ],
                default="inactive",
                max_length=50,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
